### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by mblasius** [mehrwert/TYPO3-phpMyAdmin#12]
Hello,

could you update these extension please? Thank you very much.

Best Regards
Michael

**Comment by abeutel** [comment]
Hey @mblasius, what kind of update would you like to see? Upgrading phpMyAdmin to the latest stable release or Support for TYPO3 8.1?

Best,
Andreas

**Comment by mblasius** [comment]
Hey @abeutel, sorry for my late answer. I meant an upgrade for phpMyAdmin to the latest stable release. Thank you.
Best regards
Michael

**Comment by sgrossberndt** [comment]
I think this issue can be closed?

**Comment by abeutel** [comment]
Resolved with 5.1.6.
