### ISSUE TITLE
Depreciation log entry: "Registered "tools_txphpmyadmin" as a script-based module."

### ISSUE THREAD

**Issue by kludikovsky** [mehrwert/TYPO3-phpMyAdmin#17]
I get the following entries in the depreciation log about every 5 minutes.
Seems to be an issue.
I have no glue where this comes from.

`
07-04-17 21:54: Registered "tools_txphpmyadmin" as a script-based module. Script-based modules are deprecated since TYPO3 CMS 7. Support will be removed with TYPO3 CMS 8, use the "routeTarget" option or dispatched modules instead.
07-04-17 21:54: TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModulePath() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use routeTarget or dispatched modules instead. - call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->run#20 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->handleRequest#302 // TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->boot#78 // TYPO3\CMS\Core\Core\Bootstrap->loadExtensionTables#122 // TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadExtTables#974 // TYPO3\CMS\Core\Cache\Frontend\PhpFrontend->requireOnce#1876 // TYPO3\CMS\Core\Cache\Backend\SimpleFileBackend->requireOnce#77 // require_once(typo3temp/Cache/Code/cache_core/ext_tables_d9b8e39b9bd0b2cee68920f678d4001ef82f0292.php),typo3_src-7.6.16/typo3/sysext/core/Classes/Cache/Backend/SimpleFileBackend.php#382 // TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModule#3407 // TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModulePath#950 // TYPO3\CMS\Core\Utility\GeneralUtility::logDeprecatedFunction#1006 (typo3_src-7.6.16/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php#1004)
07-04-17 21:54: TYPO3\CMS\Backend\Sprite\SpriteManager is deprecated since TYPO3 CMS 7, will be removed with TYPO3 CMS 8
`

If I can be of some help please let me know.

t3phpmyadmin: 5.1.9
T3: 7.6.16
PHP: 5.6
Debian 7

**Comment by abeutel** [comment]
Seems you have enabled the deprecation log in your TYPO3 7.6 application. The deprecation log collects warnings about extensions and code using methods that will be deprecated in future TYPO3 version. It is OK to have those warnings for pMA in TYPO3 7.6.

It is safe to ignore these messages in 7.6 but pMA will break in 8.7 so it is no compatible yet. For 8.7 we need to refactor the backend integration and will release a new version of the extension.
