### ISSUE TITLE
Make compatible with TYPO3 8

### ISSUE THREAD

**Issue by simonschaufi** [mehrwert/TYPO3-phpMyAdmin#18]
It would be great if this extension would be compatible with TYPO3 8.

**Comment by abeutel** [comment]
Yes ;-) We already gave it an unsuccessful try since the backend module integration in v8 changed significantly... Need to talk to Benni.

**Comment by simonschaufi** [comment]
I talked with Benni personally also and he told me that the big change happened already from 6 to 7 an 7 was just backwards compatible.
The main thing is that you need to use the new ``\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule()`` method.

**Comment by SvenJuergens** [comment]
@simonschaufi hi, maybe you can test and report a feedback ? With this changes https://github.com/mehrwert/TYPO3-phpMyAdmin/pull/19 phpmyadmin should run in TYPO3 8.7.x

**Comment by derhecht** [comment]
may see #20 also

**Comment by abeutel** [comment]
Hej @SvenJuergens and @derhecht - just a short heads-up: Thanks a lot for contributing, I really appreciate it and I'm currently testing and integrating your changes in 5.2 and a 6.0

**Comment by SvenJuergens** [comment]
hi, thanks for the Update :)

**Comment by abeutel** [comment]
Has been implemented in 2017 – c9c43cfecd62d783af5e13d1347d3b21eea5d8d7
