### ISSUE TITLE
Dependencies in ext_emconf.php

### ISSUE THREAD

**Issue by drummer73** [mehrwert/TYPO3-phpMyAdmin#27]
Thank you for maintaining this extension.
As far as I tested, phpMyAdmin is compatible with PHP7.2.
If you agree, pls. adjust the php dependencies in ext_emconf.php.
Users who running TYPO3 8 with PHP7.2 are not getting the extension updates via TER.

TYPO3 dependencies may need to be adjusted as well as this extension seems to be compatible with TYPO3 9.

**Comment by abeutel** [comment]
Thanks for raising this issue! I'll have a look at this and adjust the settings after testing.

**Comment by abeutel** [comment]
Implemented in 5.2.5
