### ISSUE TITLE
HTTP 403 for Javascript includes

### ISSUE THREAD

**Issue by sgrossberndt** [mehrwert/TYPO3-phpMyAdmin#31]
The extension tries to load Javascript files from the vendor directory in `EXT:phpmyadmin/Vendor/phpMyAdmin-4.8.5-all-languages/js/vendor`. The default `.htaccess` definition of TYPO3 denies access to directories named `vendor`:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/install/Resources/Private/FolderStructureTemplateFiles/root-htaccess#L289

Could the directory `EXT:phpmyadmin/Vendor/phpMyAdmin-4.8.5-all-languages/js/vendor` be moved to `EXT:phpmyadmin/Resources/Public/JavaScript/`?

**Comment by abeutel** [comment]
Good catch! Will investigate and check options.

**Comment by abeutel** [comment]
Resolved in 9826c85ef104e0aa0788ecc5edd8a12862a57fce

**Comment by sgrossberndt** [comment]
Thank you!
