### ISSUE TITLE
Vendor name must begin with Capital letter.

### ISSUE THREAD

**Issue by ashupatel1990** [mehrwert/TYPO3-phpMyAdmin#37]
i am using version 5.5.0 i am getting PHP Deprecated error like:
`PHP Deprecated:  The vendor name from tx_Phpmyadmin must begin with a capital letter. in /html/typo3/typo3_src-9.5.13/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php on line 233`

Namespace must start like this (Vendor name start with Capital letter):
so, instead of writing `namespace mehrwert\Phpmyadmin\Controller;`
Please Write `namespace Mehrwert\Phpmyadmin\Controller;`

**Comment by NitinParri** [comment]
In ext_tables.php on line 29 you have to change the m to M too.
If you don't you'll get the following error:
`Class mehrwert\Phpmyadmin\Controller\PhpmyadminController does not exist. Reflection failed.`

**Comment by abeutel** [comment]
Hey @NitinParri - thanks for finding this. Fixed in 5.6.1
