### ISSUE TITLE
phpmyadmin.css.php 403 Error

### ISSUE THREAD

**Issue by kledo-34** [mehrwert/TYPO3-phpMyAdmin#39]
Hey there,
Within the backend phpmyadmin.css.php is not accassible 403 Error, I guess this has to do with the Vendor folder name and the default .htaccess file, Iguess this is similar to #31 .
I didn't change the .htaccess file except of the staticfilecache official addition, so I think it's not just my installation.

**Comment by abeutel** [comment]
For reference: https://forge.typo3.org/issues/91612

**Comment by abeutel** [comment]
Hey @kledo-34, unfortunately I'm unable to reproduce this with a default `.htaccess` of 10.4. I see one rule w/ `vendor` here which is limited by `^` to the url starting with `vendor/...`

`RewriteRule ^(?:vendor|typo3_src|typo3temp/var) - [F]`

Could you please provide the rule you're referencing?
