### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by conpassione** [mehrwert/TYPO3-phpMyAdmin#43]
In Classes/Backend/PmaModule.php i did the folowing to get compatiblity with PHP7.4:

`22 + use TYPO3\CMS\Core\Core\Environment;`
`160 - $path_typo3 = substr(PATH_typo3, strlen($typo3DocumentRoot), strlen(PATH_typo3));`
`       + $path_to_typo3 = Environment::getPublicPath() . '/typo3/';`
`       + $path_typo3 = substr($path_to_typo3, strlen($typo3DocumentRoot), strlen($path_to_typo3));`

Maybe there is an better way, but it works for me :-)
Best Regards, Renzo

**Comment by conpassione** [comment]
Ups sorry, ther is allready a fix for that... and a Pull request

**Comment by abeutel** [comment]
The bug was not with PHP 7.4 but the usage of a deprecated and dropped TYPO3 path constant. That issue has been resolved in 5.6.3 by merging #44
