### ISSUE TITLE
The system doesn't like me!!!! (Result is opposite to the query)

### ISSUE THREAD

**Issue by kludikovsky** [mehrwert/TYPO3-phpMyAdmin#53]
![Bildschirmfoto vom 2021-04-10 16-39-32a](https://user-images.githubusercontent.com/6077916/114274255-dac4ed00-9a1d-11eb-8985-161afcba49e6.png)

The picture is self explanatory.

Version 5.6.4

The environment is DDEV on a local Linux MINT system.
Typo3 10.4.14 (just updated today)

**Comment by williamdes** [comment]
Maybe you need to report this upstream to the phpMyAdmin issue tracker, but please check using the MySQL command line before ;)

**Comment by kludikovsky** [comment]
Image has to go unter double quotes:
`"image" `instead of ``` `image` ```
